export const FETCH_WEATHER = 'FETCH_WEATHER';
export const FETCH_ERROR = 'FETCH_ERROR';
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_NAMES = 'FETCH_NAMES';
export const SELECT_COUNTRY = 'SELECT_COUNTRY';
export const CLEAR_FORM = 'CLEAR_FORM';
export const SET_TEMPERATURE = 'SET_TEMPERATURE';
